#!/usr/bin/env python3
"""Emit research.tex (publications, patents, software) from ../data/profile.json.

The site and the CV quote the same records, so they are generated from one
source rather than transcribed twice.
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(ROOT, '..', 'data', 'profile.json')))
extra = json.load(open(os.path.join(ROOT, '..', 'data', 'academic.json')))

SUBS = [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('#', r'\#'),
        ('_', r'\_'), ('$', r'\$'), ('∞', r'$\infty$'), ('–', '--'), ('—', '---'),
        ('“', '``'), ('”', "''"), ('’', "'"), ('·', r'$\cdot$')]

def tex(s):
    for a, b in SUBS:
        s = s.replace(a, b)
    return s

ME = 'Hyeon Jun Lim'

def authors(a):
    """Bold the author, and shorten lists of four or more with et al.

    Only when the author still appears in what is kept; abbreviating past his
    own position would drop his name from the entry.
    """
    names = [n.strip() for n in a.split(',')]
    if len(names) > 3 and ME in names[:3]:
        names = names[:3] + ['et al.']
    out = ', '.join(names)
    return tex(out).replace(ME, r'\textbf{%s}' % ME)

out = [r'% Generated by gen_research.py -- edit data/profile.json instead.', '',
       r'\section{Publications}']
for group in data['publications']:
    out += [r'\resumeGroup{' + tex(group['group']) + r'}',
            r'  \resumeSubHeadingListStart']
    for item in group['items']:
        out.append(r'    \resumeItem{' + authors(item['authors']) + r', ``'
                   + tex(item['title']) + r",'' " + tex(item['venue'])
                   + ', ' + item['year'] + r'.}')
    out.append(r'  \resumeSubHeadingListEnd')

out += ['', r'\section{Patents}', r'  \resumeSubHeadingListStart']
for p in data['patents']:
    also = r' Also filed: ' + tex(p['also']) + '.' if p['also'] else ''
    out.append(r'    \resumeItem{``' + tex(p['title']) + r",'' " + tex(p['id'])
               + ' (' + tex(p['status']) + '), ' + tex(p['date']) + '.' + also + r'}')
out.append(r'  \resumeSubHeadingListEnd')

out += ['', r'\section{Software Copyrights}', r'  \resumeSubHeadingListStart']
for s in data['software_copyrights']:
    out.append(r'    \resumeItem{``' + tex(s['title'])
               + r",'' Korea Copyright Commission, " + tex(s['id']) + ', '
               + tex(s['date']) + r'.}')
out.append(r'  \resumeSubHeadingListEnd')

open(os.path.join(ROOT, 'research.tex'), 'w').write('\n'.join(out) + '\n')

# Sections that exist only in the CV: awards, talks, teaching, service, skills.
ac = [r'% Generated by gen_research.py -- edit data/academic.json instead.', '']

def block(title, rows):
    ac.append(r'\section{%s}' % title)
    ac.append(r'  \resumeSubHeadingListStart')
    ac.extend(rows)
    ac.append(r'  \resumeSubHeadingListEnd')
    ac.append('')

def line(left, right):
    return r'    \resumeLine{%s}{%s}' % (left, right)

block('Invited Talks', [
    line("``" + tex(t['title']) + ",'' " + tex(t['venue']), tex(t['date']))
    for t in extra['talks']])

block('Awards and Honors', [
    line(r'\textbf{%s}, %s' % (tex(a['title']), tex(a['org'])), tex(a['date']))
    for a in extra['awards']])

block('Teaching', [
    line(r'%s, %s' % (tex(t['title']), tex(t['org'])), tex(t['period']))
    for t in extra['teaching']])

block('Academic Service', [
    line('Reviewer, %s%s' % (tex(s['venue']),
                             ' (%s)' % tex(s['note']) if s.get('note') else ''),
         tex(s['date']))
    for s in extra['service']])

block('Technical Skills', [
    r'    \resumeItem{\textbf{%s} --- %s}' % (tex(g['group']), tex(', '.join(g['items'])))
    for g in extra['skills']])

open(os.path.join(ROOT, 'academic.tex'), 'w').write('\n'.join(ac) + '\n')

print('research.tex:',
      sum(len(g['items']) for g in data['publications']), 'papers,',
      len(data['patents']), 'patents,', len(data['software_copyrights']), 'software')
print('academic.tex:', len(extra['awards']), 'awards,', len(extra['talks']), 'talks,',
      len(extra['teaching']), 'teaching,', len(extra['service']), 'service,',
      len(extra['skills']), 'skill groups')
