#!/usr/bin/env python3
"""Emit research.tex (publications, patents, software) from ../data/profile.json.

The site and the CV quote the same records, so they are generated from one
source rather than transcribed twice.
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(ROOT, '..', 'data', 'profile.json')))

SUBS = [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('#', r'\#'),
        ('_', r'\_'), ('$', r'\$'), ('∞', r'$\infty$'), ('–', '--'), ('—', '---'),
        ('“', '``'), ('”', "''"), ('’', "'"), ('·', r'$\cdot$')]

def tex(s):
    for a, b in SUBS:
        s = s.replace(a, b)
    return s

def authors(a):
    return tex(a).replace('Hyeon Jun Lim', r'\textbf{Hyeon Jun Lim}')

out = [r'% Generated by gen_research.py -- edit data/profile.json instead.', '',
       r'\section{Publications}']
for group in data['publications']:
    out += [r'  \resumeSubHeadingListStart',
            r'    \resumeItem{\textit{' + tex(group['group']) + r'}}']
    for item in group['items']:
        out.append(r'    \resumeItem{' + authors(item['authors']) + r', ``'
                   + tex(item['title']) + r",'' " + tex(item['venue'])
                   + ', ' + item['year'] + r'.}')
    out.append(r'  \resumeSubHeadingListEnd')

out += ['', r'\section{Patents}', r'  \resumeSubHeadingListStart']
for p in data['patents']:
    also = r' Also filed: ' + tex(p['also']) + '.' if p['also'] else ''
    out.append(r'    \resumeItem{``' + tex(p['title']) + r",'' " + tex(p['id'])
               + ' (' + tex(p['status']) + '), ' + tex(p['date']) + '.' + also + r'}')
out.append(r'  \resumeSubHeadingListEnd')

out += ['', r'\section{Software Copyrights}', r'  \resumeSubHeadingListStart']
for s in data['software_copyrights']:
    out.append(r'    \resumeItem{' + authors(s['authors']) + r', ``' + tex(s['title'])
               + r",'' Korea Copyright Commission, " + tex(s['id']) + ', '
               + tex(s['date']) + r'.}')
out.append(r'  \resumeSubHeadingListEnd')

open(os.path.join(ROOT, 'research.tex'), 'w').write('\n'.join(out) + '\n')
print('research.tex:',
      sum(len(g['items']) for g in data['publications']), 'papers,',
      len(data['patents']), 'patents,', len(data['software_copyrights']), 'software')
